language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
  - master
  
before_script:
- npm run build --if-present

script:
- npm run test-headless
- ng build --prod --base-href https://christopherhaney.github.io/geocorona/

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/geocorona
    on:
      branch: master