@startuml geocorona
[App] - [NavBar]
[NavBar] - Map
[NavBar] - [About]
package "Map" {
    [DataService] ..> COVID_API_URL : gets
    [DataService] - [MapService] : feeds
    [MapService] - [UsaMap] : generates
}
@enduml